### ISSUE TITLE
Don't wrap UI operations in unimports when bitcoin signing

### ISSUE THREAD

**Issue by mmilata** [trezor/trezor-firmware#1132]
Follow up of #1108. The unimports are _probably_ not needed and make the code less readable.

Question: can removing the unimports cause the firmware to run out of memory? Is running the device tests (on an actual device) enough to check that it doesn't happen?

**Comment by matejcik** [comment]
It could in theory, but I believe we have large enough margins for Bitcoin signing in particular.

The best way to figure out if that doesn't happen is to run some tests with the white-noise homescreen set. @bosomt is skilled at that .)
Perhaps we could make a special FW build where the white-noise homescreen is the default? So that this can run the device-tests suite?

**Comment by sorooris** [comment]
Blocked by #1222

**Comment by bosomt** [comment]
just sent this TEST 10k size + transaction + whitenoise background with 2.3.3 rev df5421e
https://tbtc1.trezor.io/tx/2150d8402380cca111f59c01d053023df7697d8e749729efc64425601fc7331b

@tsusanka @matejcik is that enough ? /+ is this model T specific ? /

**Comment by matejcik** [comment]
yes and yes

**Comment by sorooris** [comment]
**QA OK**
Device: 2.3.3 df5421e + white noise homescreen
Suite [3095a174f258c0226faf2ebcbdda3d8b7f04686f](https://github.com/trezor/trezor-suite/commits/3095a174f258c0226faf2ebcbdda3d8b7f04686f)
