### ISSUE TITLE
Remove Prompt Always from safety_checks

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1268]
As discussed on meetings. We want to be strict and then enable it if necessary.

**Comment by andrewkozlik** [comment]
I think the internal discussion is inclined to keep the `prompt_always` setting, me included. I am summarizing the arguments formulated by @stick and @matejcik, so that they don't get lost:
- avoid crippling the user experience of Casa and anyone that has a different use-case for Trezor than we defined
- "prompt always" mode is in a released firmware already, removing it would do more harm than good
- if we want to do #1260 (skip prevtx streaming), it makes sense that some people with some software would want it always allowed (think Suite + pruned node)

**Comment by tsusanka** [comment]
Since the firmware is out already for almost half a year, I agree this could do more harm than good. Closing.
