### ISSUE TITLE
Support signing payjoin proposal PSBTs

### ISSUE THREAD

**Issue by craigraw** [trezor/trezor-firmware#1340]
**Is your feature request related to a problem? Please describe.**
A payjoin (BIP78) proposal PSBT contains an additional input which has already been signed by the receiver, and contains the `final_scriptwitness` field. The sender's inputs on this PSBT must however still be signed as per normal. Currently, Trezor fails to recognise it does not need to check/sign the additional input, and fails with `Previous transaction b'ffff...' not available` (in this case because the `non_witness_utxo` is not present).

**Describe the solution you'd like**
Trezor should not need to check the additional input as thoroughly as it does not need to sign it. It should parse the proposal PSBT as valid, check/sign the sender's inputs as normal, and leave the additional input unchanged.

**Comment by matejcik** [comment]
There is support for this since #1080. As long as the host sets the correct `EXTERNAL` input script type, provides valid previous transaction info and a valid signature of the external input, it is possible to send payjoined transactions.

I believe this bug should be filed against HWI, or whatever host-side software that is not providing the necessary info.

FWIW, this is untrue:
> Trezor should not need to check the additional input as thoroughly as it does not need to sign it.

Trezor must validate that the additional input already has a valid signature, otherwise we open an interesting class of attacks where it's possible to get the user to sign two invalid transactions and combine them into a valid one sending bigger amount.
