### ISSUE TITLE
Explicitly confirm turning off replacement possibility during a replacement

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1343]
We currently do not confirm the transaction "replacement possibility" (also called RBF sometimes). Neither during the initial sign nor during a replacement process. We have discussed this in Product and we would like to keep the initial signing as is (without any confirmation) not to confuse users, but we would like to have an explicit dialog when the user tries to "finalize" the transaction (removing the replacement possibility).

The particular wording is to be defined by @matejzak when he completes the design in Suite.

**Comment by andrewkozlik** [comment]
@matejzak or @tsusanka please clarify some details. I can see four scenarios:
1. If the original transaction **allows RBF** and the replacement transaction **allows RBF**, then keep dialogs as they are currently.
2. If the original transaction **allows RBF** and the replacement transaction **is final**, then show the new finalization dialog.
3. What if the original transaction **is final** and the replacement transaction **allows RBF**? This might seem like nonsense, but the original might have never been sent to the network or it might have been kicked out of the mempool for example due to timeout or due to mempool size limit. So I think technically it is legit. The options are to:
    a) Show no additional dialog.
    b) Show an "unfinalization" dialog.
    c) Fail signing.
4. Similarly, what if the original transaction **is final** and the replacement transaction **is final**? Again might seem like nonsense, but technically it is legit for the same reasons as above.
    a) Show no additional dialog.
    b) Fail signing.

**Comment by tsusanka** [comment]
1. Yes.
2. Yes.
3. Failing signing. You can still sign a new transaction no need for the replacement workflow.
4. Failing signing.

We can discuss the details on standup.

**Comment by andrewkozlik** [comment]
Based on what we discussed at the standup, we could have the following screens in Case 2 (finalization):

![image](https://user-images.githubusercontent.com/42678794/99675744-e10afa80-2a77-11eb-9138-2f7321e53d54.png) ![image](https://user-images.githubusercontent.com/42678794/99675791-f08a4380-2a77-11eb-9215-91b7ea89327e.png)

and if there is no fee change, then the following (ignore that the fee amounts are different):

![image](https://user-images.githubusercontent.com/42678794/99675744-e10afa80-2a77-11eb-9138-2f7321e53d54.png) ![image](https://user-images.githubusercontent.com/42678794/99676147-6db5b880-2a78-11eb-9b0a-35d58a6e57a4.png)

In Case 1 (no finalization) we would keep the current screens:

![image](https://user-images.githubusercontent.com/42678794/99676222-82924c00-2a78-11eb-8ff4-1182f141c0d3.png) ![image](https://user-images.githubusercontent.com/42678794/99675791-f08a4380-2a77-11eb-9215-91b7ea89327e.png)

In Cases 3 and 4 I am inclining towards showing allowing them and showing no additional dialog at least in the PayJoin scenarios, which would keep looking like this if the user's fee contribution is increasing:

![image](https://user-images.githubusercontent.com/42678794/99677838-71e2d580-2a7a-11eb-8425-aecaacea9ce9.png) ![image](https://user-images.githubusercontent.com/42678794/99675791-f08a4380-2a77-11eb-9215-91b7ea89327e.png)

or simply like this if the *user's* fee contribution is decreasing:

![image](https://user-images.githubusercontent.com/42678794/99677838-71e2d580-2a7a-11eb-8425-aecaacea9ce9.png)

**Comment by andrewkozlik** [comment]
I just realized another reason why allowing Cases 3 and 4 makes sense. Even if an original transaction appears finalized, it may have inherited RBF opt-in if one of its ancestors opted-in to RBF and remains unconfirmed, which we can't detect on Trezor.
