### ISSUE TITLE
Allow decreasing the output value in RBF transactions

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#1491]
Currently we don't allow user to decrease output values during the RBF process.

We could allow this providing the following is met:
* all output values are either staying the same or they are decreased, i.e. no output value increase allowed
* for each changed output we'll show a confirmation dialog with output (address), delta amount and final amount

**Comment by andrewkozlik** [comment]
Here are some screenshots of the current WIP. In this example we are taking 0.0001 from an external output and 0.0009428 from a change output to bump the fee from 0.0000378 to 0.0010806.

![image](https://user-images.githubusercontent.com/42678794/109039302-ead27880-76cc-11eb-92e1-3a68c6c40d07.png) ![image](https://user-images.githubusercontent.com/42678794/109039314-edcd6900-76cc-11eb-94b7-cc62d7b52afd.png) ![image](https://user-images.githubusercontent.com/42678794/109039320-f02fc300-76cc-11eb-98f8-a0bbb62b10f4.png) ![image](https://user-images.githubusercontent.com/42678794/109039326-f32ab380-76cc-11eb-804b-2a0f63a3e9d5.png)

It's hard to fit the output modification on a single screen, because the address can take up more than two lines. Here is an earlier attempt, where the new amount can easily overflow the screen:

![image](https://user-images.githubusercontent.com/42678794/109040420-29b4fe00-76ce-11eb-896b-02cbaef5d361.png)

**The same flow on TT:**

![image](https://user-images.githubusercontent.com/42678794/109039911-a09dc700-76cd-11eb-9623-74fcdcbba70c.png) ![image](https://user-images.githubusercontent.com/42678794/109039922-a3002100-76cd-11eb-8be3-fc091c1fd179.png) ![image](https://user-images.githubusercontent.com/42678794/109040070-d04ccf00-76cd-11eb-8d84-11fe493055ba.png) ![image](https://user-images.githubusercontent.com/42678794/109039940-a85d6b80-76cd-11eb-9e31-9208a25a0949.png)

**Comment by prusnak** [comment]
I like these screens 👍

**Comment by andrewkozlik** [comment]
The use-case that we are trying to solve by this is fee bumping when the original transaction is transferring the entire account balance ("Send Max"), in which case the only option is to take the fee bump from the external output. I am wondering, do we want to enforce that the decrease in the output amount is always used towards the fee, i.e. that it doesn't go back to the user's change address? I don't see any strong arguments either way, but I am curious if anyone has any opinion on this.

**Comment by prusnak** [comment]
> I am wondering, do we want to enforce that the decrease in the output amount is always used towards the fee

Yes. We want this. That's why I wrote that none of the outputs' values are being increased in the process. Otherwise we'd allow users to create double-spends very easily.

**Comment by andrewkozlik** [comment]
> > I am wondering, do we want to enforce that the decrease in the output amount is always used towards the fee
> 
> Yes. We want this. That's why I wrote that none of the outputs' values are being increased in the process. Otherwise we'd allow users to create double-spends very easily.

Summary of follow-up discussion IRL:
- A malicious user can always use trezorctl or a third-party tool to create double-spends simply by sending two SignTx requests to Trezor for two transactions that have the same inputs. Preventing _easy_ creation of double-spend transactions needs to be handled by Suite. It is infeasible for the firmware to prevent this.
- In general there are cases where it makes sense to increase the output values in the replacement transaction:
    - Increase/create a change-output if a new input was added to cover the fees.
    - Increase/create an external output in case of a PayJoin. The funds for the increase have to come from a new external input.

So far there doesn't seem to be any problem with allowing increasing of change-outputs in any scenario. As for external outputs, I think it makes sense to split it into two scenarios:
- Non-PayJoin: _Allow decreasing_ of external output amounts and _disallow increasing_ of external output amounts.
- PayJoin: _Allow increasing_ of external output amounts and _disallow decreasing_ of external output amounts, because allowing both would add some extra complexity, which we don't seem to need right now. (The Send Max + PayJoin scenario seems like an edge case not worth solving at the moment. By "extra complexity" I mean that we would need to ensure that the decrease in external output amounts goes entirely towards the fee, i.e. add another variable like `orig_external_decrease` to the `Approver` and check and present it correctly in the UI. We can always do that in the future if the need arises.)

**Comment by andrewkozlik** [comment]
One more comment about the UI on T1. I can make it possible to go back and forth between the "Modify amount for address" screen and "Decrease amount by" screen, since logically they are the same screen and on the TT the user can swipe back and forth between them. @matejzak let me know if you'd like that, otherwise let's leave it for the UI redesign.
