### ISSUE TITLE
Add The https://Crypto.org Chain | CRO mainnet

### ISSUE THREAD

**Issue by arno01** [trezor/trezor-firmware#1550]
**Is your feature request related to a problem? Please describe.**

The https://Crypto.org Chain application is now supported by @Ledger https://twitter.com/cryptocom/status/1375324607540948996

Can't see any reason why not Trezor now.

Crypto.com / .org => are now having 10+ million users.
That'd benefit a lot of Trezor wallet holders.

**Describe the solution you'd like**
adding CRO mainnet token support.

**Describe alternatives you've considered**
I love Trezor, but it's missing CRO... Ledger does support CRO, and I can't see any reason why not to support it.

**Additional context**

They went live on 25.03.2021.

https://crypto.org/explorer/
https://github.com/crypto-org-chain/chain-main
https://crypto.org/docs/
https://crypto.org/releases

**Comment by matejcik** [comment]
Unfortunately, we do not have the capacity to add new coins to the firmware right now. Also our current product goal is to unite what we support in firmware and in Trezor Suite and since firmware is way ahead of Suite we want to pause for a bit, implement the remaining coins into Suite and then consider adding new coins. Thank you for your understanding.
