### ISSUE TITLE
Device repeatedly flashes after reconnecting during Shamir backup and blocks seed recovery

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-firmware#1631]
**Describe the bug**
When user disconnects the device safely (i.e. after completing at least one share) during Shamir backup, device then repeatedly flashes and makes it unable to complete the seed recovery. 
This repeated blinking is continuous in Wallet and user cannot complete the recovery.
In case of Suite, bliking will stop when Suite fully loads. 
Every time the device flashes, it returns the user back to the starting screen (the one that informs the user how many shares are needed for seed recovery).

**Firmware version and revision**
Firmware TT 2.4.0 d80d5456

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Wallet 249daf21e2f8380c89c3e4b46c976851c50afec0 
                              Trezor Suite 21.5.1 4d09d88476dab2e6b2fbfb833b749e9ac62251c2
 - OS: nixos 21.03
 - Browser Chromium Version 88.0.4324.182 (Official Build) (64-bit)

**To Reproduce**
1. Wipe device
2. Enter first share of shamir seed
3. Disconnect and reconnect device
4. Try to unsuccessfully complete the seed recovery

**Expected behavior**
User will be able to complete the Shamir recovery. 

**Videos**
[here](https://drive.google.com/drive/folders/1xprv89jeds5Rd2cUn3U-AJo6Rnz7SA79?usp=sharing)

**Comment by andrewkozlik** [comment]
The wallet is sending `Initialize` and `GetFeatures` repeatedly and every time it happens, it interrupts and resets the recovery workflow. @matejcik could this be related to the workflow restarts?

**Comment by matejcik** [comment]
Most likely, yes. I will look into it.

**Comment by matejcik** [comment]
It seems that before workflow restarts, silent messages would not interrupt the recovery workflow because they would be handled without touching the running process.

Now, the running processes are cleared after every workflow, even the silent ones.

The way to avoid the problem is probably not restarting for `Initialize` and `GetFeatures` -- perhaps only in the recovery homescreen mode, to keep some of the nice properties.

Hypothetically we could also fix this on the Wallet side by not hammering the device while the recovery is ongoing. But IIRC there are some obstacles. The Suite runs a fundamentally different process: after discovering that the device is in recovery mode, it calls `RecoveryDevice` and hooks into the workflow. (This will _always_ kill the current progress; so blinking before Suite is fully loaded is pretty much a non-issue, you'd need to wait for full load anyway.)
...the Wallet on the other hand might not be capable of doing that without significant modifications, so repeatedly looking at `Features` to see if the recovery is done already is the only reasonable thing it can do.

**Comment by tsusanka** [comment]
If we can avoid it, it would be best not to do any changes in Wallet 🙏.

**Comment by matejcik** [comment]
@wendys-cats can you test with FW from this pipeline? https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/pipelines/309747212

**Comment by wendys-cats** [comment]
@matejcik on it! Will post outcome here

**Comment by matejcik** [comment]
> **NOK Persists in Suite**
> Problem seems to be the ability to start the share recovery on device without any interaction from Suite, meaning Suite displays "Reconnect your Trezor", but user is already able to type in the share recovery, and once Suite starts loading, it will reset the action back to starting point.

Is this different from the previous firmware version? Please describe expected/actual process.

also if you're updating a comment with significant new information, please write a _new comment_, your edit did not show up as a notification for me :(

**Comment by wendys-cats** [comment]
@matejcik I apologize, I did not realize you will not get the notification for the edit.

**Actual**
The issue is the same for the previous release candidate d80d5456 and the current one 071c6c06. It happens only while the Suite is loading, but once the Suite fully loads after reconnecting the device (which can take some time) it does not happen. 
Tried it with 2.3.6 public and it is also present. 

**Expected**
Suite will not restart the shamir seed restoration proccess - either by disallowing the device to start the recovery before Suite loads or by other means.

**Comment by matejcik** [comment]
> Tried it with 2.3.6 public and it is also present.

This is what I was thinking.
If I may summarize:

1. It is possible to start entering shares before Suite is fully loaded.
   => this is **by design**. It is also possible to start entering shares when running off a powerbank, fully air-gapped.
2. Once Suite fully loads, it interrupts the share currently being entered
   => this is a **known limitation**, otherwise it's difficult for Suite to hook into the progress reporting.

Are there any other points besides the two above?
In particular, _one interruption_ from Suite is expected, but multiple interruptions would be a bug.
Also in the video it looked a little like the Suite waiting for you to start entering shares?

If no other points, let's consider the original issue (flashing after reconnecting) as fixed.

**Comment by wendys-cats** [comment]
@matejcik 

Yes, that would be the gist of it. 
However, the amount of interrupts from Suite varies, it is not just once. [Here](https://drive.google.com/drive/folders/1xprv89jeds5Rd2cUn3U-AJo6Rnz7SA79) (Suite video for the issue I originally provided) shows that Suite interrupts the proccess several times. The [second](https://drive.google.com/drive/folders/1xprv89jeds5Rd2cUn3U-AJo6Rnz7SA79) video provided in the comment only shows one interruption.

**Comment by matejcik** [comment]
Before this fix, there would be multiple interrupts. With it, there should be only one -- otherwise it's either FW or Suite bug

**Comment by andrewkozlik** [comment]
> 2\. Once Suite fully loads, it interrupts the share currently being entered
>     => this is a **known limitation**, otherwise it's difficult for Suite to hook into the progress reporting.

I agree with @wendys-cats that this behavior is unexpected, but I also agree that it's not a regression and that it's not high priority, because it's just a nuisance. The flow is getting reset because of the `RecoveryDevice` message that is being sent by Suite. As I understand it, resetting the flow in Trezor is required so that Suite will be able to count the button requests and show recovery progress (which it actually isn't doing yet). So I think this issue should be solved as part of https://github.com/trezor/trezor-firmware/issues/35 and Trezor should be able to hook the `RecoveryDevice` message into the ongoing recovery workflow without restarting it.

**Comment by bosomt** [comment]
is it me or is it same issue i created year ago and it was ignored ? :)

https://github.com/trezor/trezor-suite/issues/2049#issuecomment-654755555

**Comment by matejcik** [comment]
@bosomt probably, yes :) my guess is it was ignored because at that time we _knew_ this is happening.
