### ISSUE TITLE
Support for ICP (Dfinity)

### ISSUE THREAD

**Issue by lf94** [trezor/trezor-firmware#1712]
**Is your feature request related to a problem? Please describe.**

ICP is now trading but there is zero hardware wallet support. It'd be fantastic if Trezor supported this.

**Describe the solution you'd like**

Whatever allows ICP to be stored and transferred from a Trezor device. While I would love support for Trezor One, it can be solely for Trezor T.

**Describe alternatives you've considered**

Ledger, but Ledger also does not support it, and I'm not a Ledger fan.

**Additional context**

None

**Comment by matejcik** [comment]
Hello, our current product goal is to unite what we support in firmware and in Trezor Suite and since firmware is way ahead of Suite we want to pause for a bit, implement the remaining coins into Suite and then consider adding new coins.

For that reason, we are currently not adding nwe coin implementations to Trezor. Thank you for your understanding.
