### ISSUE TITLE
Be stricter about downloading the Alpine container

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#1714]
https://walletscrutiny.com/hardware/trezorOne/ points out that we just download a container from Alpine CDN, without even using https.

We should at least be checking its hash against a known value.

**Comment by matejcik** [comment]
@vdovhanych maybe you could look into this?

**Comment by matejcik** [comment]
the download happens in `environment.yml` and in `build-docker.sh`

**Comment by vdovhanych** [comment]
Well, we do not download a container from the Alpine CDN. We download Alpine minirootfs itself and create the container with it as a base. I think that it's done this way as there is no minirootfs version on the docker hub. We should change it to https, though. Or another option would be to use the full Alpine image and get it from the hub directly in `Dockerfile` instead of `FROM scratch`, use `FROM alpine:3.14.0` and build it. `build-docker.sh` isn't used anywhere in the ci I assume it for local building but that should also be changed to https.

**Comment by prusnak** [comment]
Let's just change to https and check the sha256 hash of the downloaded file.
