### ISSUE TITLE
RSOD after canceling FW install prompt on device with Suite closed

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-firmware#1859]
**Describe the bug**
TT device is switched to bootloader mode to enable FW installation via Suite and Install firmware button is clicked on, prompting device to ask user if they want to install new firmware. Once the install prompt is present on device, user cancels it and then either reloads Suite, or closes and opens a new Suite instance, device gets a RSOD (Suite does not need to be reloaded before canceling the install prompt).

**Info:**
 - Remembered Wallet: no
 - Suite Version: APP AND WEB 21.10.2 3cb57ea
 - Browser: , version
 - OS: Windows10 AND macOS Big Sur 11.6 (intel)
 - Bridge: build version
 - Firmware Version: TT FW 2.0.5 AND 2.4.0 public

**Steps to reproduce:**
**1.** Initiate Update firmware action
**2.** Reboot to bootloader mode
**3.** Click "Install firmware" button
**4.** Close Suite OR Reload Suite (and skip to step 8)
**5.** Cancel install firmware on device
**6.** Device stays in BL
**7.** Open Suite
**8.** RSOD

**Expected result:**
Device will reconnect to Suite in bootloader mode.

**Actual result:**
RSOD.

**Screenshots:*
![photo_2021-10-19_09-43-13](https://user-images.githubusercontent.com/58593111/137867534-25f7b662-034d-4225-bcaa-505c65c7d29a.jpg)
*

**Comment by tsusanka** [comment]
Ping @hiviah, some progress on this?

**Comment by hiviah** [comment]
@tsusanka 

As the bootloader write is blocking and requires the client to read the data back, I'd consider it more of a security feature (resilience against race conditions). USB requires you open data connection and read from it from one client. RSOD happens when you write data on device and don't read it back on client.

In firmware you can do the same race, except that you will desync your client with device. Which AFAIK is not exploitable, but also generally not desirable/expected as a part of proper flow.

I'd close this, since there is no proper handling possible, it's result of race condition.

**Comment by tsusanka** [comment]
Okay, thanks for the info! So I am indeed closing this as `won't fix` as this is a) somewhat an edge-case b) is a security feature. Feel free to reopen if someone disagrees.

**Comment by matejcik** [comment]
couldn't we change the error from RSOD to something user-facing though?

but perhaps that is a different issue; in particular, a similar user-facing screen should be shown in case of "failed USB read" or "failed USB write" in firmware, which are known states that in most cases indicate a bad cable.
