### ISSUE TITLE
Implement blind EIP-712 signing for Trezor T

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#2015]
For compatibility with https://github.com/trezor/trezor-firmware/pull/1970, we also want to implement `EthereumSignTypedDataHash` in TT, in addition to the already existing `EthereumSignTypedData` functionality.

The new workflow will accept domain hash and message hash from the host, show them for confirmation, and then produce the EIP-712 signature.

Open point: should this be preceded by a warning screen about blind signing?

**Comment by yura-pakhuchiy** [comment]
Why not implement support `EthereumSignTypedData` in connect instead (or prioritize implementing)? Trezor argued that blind signing is evil for years, and now completely changing direction, just doing same bad thing Ledger do and even considering now showing a warning ¯\_(ツ)_/¯.

**Comment by yura-pakhuchiy** [comment]
More over, it is highly likely, that if `EthereumSignTypedDataHash` arrives first for both T1 and TT, then we probably will never see proper `EthereumSignTypedData` support, because it will be very low priority for both connect/metamask/other wallets.

Blind signing results is hacks like this: https://fullycrypto.com/nexus-mutual-founder-loses-8-million-after-metamask-hack
I understand that it is difficult to deliver proper signing on T1, and hashed signing makes sense for it. But delaying connect part for proper signing and implementing flawed signing in TT is very irresponsible.

**Comment by matejcik** [comment]
Thanks for your input guys :) We decided to go with the better solution in the end, tracked in https://github.com/trezor/connect/pull/983.
I'm still keeping #2019 open in case we need that code, but it will probably go away once new Connect is out.
