### ISSUE TITLE
different wallet addresses for the same 24 words seed

### ISSUE THREAD

**Issue by lihaibh** [trezor/trezor-firmware#2068]
Ive upgraded the trezor model T firmware to the current latest version: `2.4.3`.
Ive created a 24 word seed on trezor connected it to yoroi and then tried to restore the same wallet using the same seed on Yoroi and received different wallet addresses. According to this resolved issue: #1783 i thought this problem will be fixed.

**Comment by matejcik** [comment]
That's not how #1783 works, unfortunately. Yoroi would need to be updated to make use of the new compatibility mechanism, otherwise it will (correctly!) keep doing what it's been doing before.

The issue here is that if we simply changed the address derivation method to match Yoroi's hot wallet, this would destroy pre-existing accounts of people who have been using 24-word seeds with Trezor and Yoroi before the change was implemented.

So the compatibility mode is opt-in, and Yoroi would have to enable it. Otherwise you get the same incompatible addresses as before.
