### ISSUE TITLE
PIVX no longer works.  

### ISSUE THREAD

**Issue by chilly2k** [trezor/trezor-firmware#2146]
TREZOR 1 firmware 10.5.0

  I have been using the TREZOR 1 along with the SPMT tool, for several years,  to manage my PIVX masternodes.   Last week I was going to sweep my rewards, but it started to fail with "coin not found".  Needless to say I went through several gyrations, including resetting the trezor and reloading my seed.  Final found the github issue to pull support.  

   The github issue said that SPMT was not a wallet.  and no wallet support was available.  I'm not sure what the definition of a wallet is?   SPMT allows you to send and receive coins.  It doesn't handle the blockchain but neither does an electrum wallet.  It uses known hosts, or the user can supply their own local host.  
 
    Please consider adding this back ASAP.  Thanks Bob

**Comment by prusnak** [comment]
PIVX was removed in Firmware 1.9.4 because there was no PIVX wallet with Trezor support.

If you need to use PIVX with Trezor, downgrade the firmware to version 1.9.3 or older. That said, the downgrade will erase the storage, so you'll need to recover the device from your recovery seed.

We are not adding PIVX back, because it has since become irrelevant.
