### ISSUE TITLE
Unable to use Trezor Model T as security key on Google with Safari

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2205]
**Describe the bug**
Adding Trezor Model T as a security key to Google fails.

**Firmware version and revision**
2.4.3

**Desktop/smartphone setup (please complete the following information):**
 - OS: macOS
 - Browser Safari 
 - Version 15.3

**To Reproduce**
1. Go to https://myaccount.google.com/signinoptions/two-step-verification
2. Authenticate
3. Click 'Add Security Key'
4. See 'Got your security key?' modal and click 'Next'
5. Press the green tick 

**Expected behavior**
Successful pair Model T to Google account

**Screenshots**
![P_20220330_151851(1)](https://user-images.githubusercontent.com/216917/161536893-77917b43-8371-4f1a-838b-3670e4383d30.jpg)
![Screenshot 2022-04-04 at 13 32 20](https://user-images.githubusercontent.com/216917/161536924-399e97f6-da1a-4111-abd4-37a10717f8c0.png)

**Additional context**
Model 1 works.

**Comment by sime** [comment]
@mcudev Just to clarify, the issue is with Google.com ?

**Comment by mcudev** [comment]
@sime yes, google.com. testing again today, i find that things are working a little better/differently with chrome version 101.0.4951.64 (Official Build) (64-bit).

now, i can get my key registered with the "FIDO2 Register" process and working with this google accounts + chrome combo, there is just one workaround that i had to do. when registering the key, i get this screen:

![allow_skip](https://user-images.githubusercontent.com/29890609/168420655-30bff5a3-3a7c-4d1e-89df-0d6fe24255a8.png)

if you click allow, the process fails with:

![could_not_connect](https://user-images.githubusercontent.com/29890609/168420665-07a10027-6f2f-4138-b271-cb5afa88f2f5.png)

when you click skip, you can name the key and continue on and things work. also, when logging in using the fido2 authenticate process, with this google + chrome combo, it actually lets me in instead of seeming like it works and then forcing me to use a fallback 2fa mechanism.

firefox still uses the u2f authenticate process and that still works too.

**Comment by sime** [comment]
Can confirm it is failing for me on Chrome and Safari.

**Comment by andrewkozlik** [comment]
Reopening. PR #2834 only fixes https://github.com/trezor/trezor-firmware/issues/2205#issuecomment-1109755886 for Chrome.

**Comment by bosomt** [comment]
I can confirm that it does not work on my Safari + macOS ;)

 - Device: model T 2.5.4 Universal (revision 0a955b4ad6d9fb5e7a1dbd3333548ffd8b33399a)
 - Safari Version 16.3 (18614.4.6.1.5)
