### ISSUE TITLE
Build Model R for Mac users

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2292]
Reference to issue in `trezor-user-env` repo: https://github.com/trezor/trezor-user-env/issues/176

**Comment by grdddj** [comment]
Pushed as a part of https://github.com/trezor/trezor-firmware/pull/2277, as it makes sense only in connection with all the new input features (PINe entry, seed recovery etc.).

As for the `trezor-user-env`, the `R` emulator seems to work fine there. However, I don't want to merge it yet, as there seem to be issues with screenshotting - that could have been caused by the custom installation of `trezorlib`. I am investigating that.

For the time being, if anybody wants to use the model `R`, they need to supply `:178` tag at the end of the image ([Linux](https://github.com/trezor/trezor-user-env/blob/master/docker/compose.yml#L5), [MAC](https://github.com/trezor/trezor-user-env/blob/master/docker/compose.yml#L14))
