### ISSUE TITLE
Broken build with python 3.8

### ISSUE THREAD

**Issue by TychoVrahe** [trezor/trezor-firmware#2305]
Latest changes (#2286)  broke build with python 3.8 and older due to some type annotations.

As python 3.8 is a default in some widely used OSs ( Ubuntu 20.04.4 LTS), it would make sense to support this version.

Nice to have would be to also test with the minimal python version in CI pipelines

**Comment by prusnak** [comment]
Btw, reproducer is:

```
$ make gen
...
  File "...trezor-firmware/common/tools/coin_info.py", line 51, in <module>
    SupportInfo = dict[str, SupportInfoItem]
TypeError: 'type' object is not subscriptable
```

**Comment by matejcik** [comment]
It seems easy enough to keep 3.7 or 3.8 compatibility. what i'm wondering about is how to ensure that breakages like this don't happen.

trezorlib runs tox over all supported Python versions so that is covered. the internal tooling, not at all. One way would be to set the nix env to use Python 3.8, but that is slightly complicated IIRC.
Maybe we have a linter available that would tell us this, and could run it as part of the `python test` CI job, where different Pythons are available?
