### ISSUE TITLE
Create a tool to upload and display static image

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#235]
Petr (UX designer) asked for a tool, which would upload a static image (like PNG) to trezor device, so he can have a look what it looks like at Trezor.

We have a converter from PNG in `tools/` and I can use `res.load` to show the image?

If that's the case, it should be pretty quick.

**Comment by tsusanka** [comment]
@prusnak could you estimate how difficult this is? If it's a quick thing I think we might do it asap? So Petr can use it

**Comment by prusnak** [comment]
Yes, I'll do it.

**Comment by prusnak** [comment]
Added a quick hack to [toif-upload](https://github.com/trezor/trezor-firmware/tree/toif-upload) branch.

It modified ApplySettings.homescreen field to overwrite whatever is on the screen right now, instead of setting a home screen.

Also, there is a tool `core/tools/toif_upload` which takes 240x240 RGB (no alpha) PNG file as a parameter and uploads it to the device.

**Comment by tsusanka** [comment]
I have rebased the toif-upload branch on top of master.

**Comment by tsusanka** [comment]
@prusnak how difficult would it be have the same functionality for T1? Petr would really really make use of it :)

**Comment by prusnak** [comment]
Relatively easy.

**Comment by prusnak** [comment]
For T1 we can use a set homescreen feature. The homescreen can be set from the web wallet or using `trezorctl set homescreen -f filename`
