### ISSUE TITLE
Fix bootloader build check in CI

### ISSUE THREAD

**Issue by TychoVrahe** [trezor/trezor-firmware#2621]
CI missed that https://github.com/trezor/trezor-firmware/pull/2576 breaks bootloader build.

Would be nice if we could detect the `Signature is INVALID, hashes are MISSING` as an error too.

Relevant CI job: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/3257193796

**Comment by mmilata** [comment]
It's already there? Unless this issue is regarding TR. https://github.com/trezor/trezor-firmware/blob/master/ci/build.yml#L26

**Comment by TychoVrahe** [comment]
right. missed that. so the CI check just doesn't work properly, since it didn't detect that the bootloader build is broken

**Comment by mmilata** [comment]
Looks like `core/tools/headertool.py` returns 0 exit code regardless of signature/hashes.

**Comment by matejcik** [comment]
Properly parsed file, regardless of signature/hashes status, is a success for headertool so that part is right though?

There are two parts to #2616:
(a) headertool is supposed to write correct hashes into the header, which it didn't do because as part of the refactor having the hashes is now not a prerequisite for signing. this is a bug that needs to be fixed
(b) headertool currently does not recognize DEVEL signatures for bootloader, which is more of a missing feature that needs to be re-added
neither of which make sense to catch via CI, unless we have an independent tool that verifies the result of headertool

This suggests to me that the CI part is in fact correct and we can close this issue?

**Comment by TychoVrahe** [comment]
Ok sounds good enough
