### ISSUE TITLE
T2B1 design - Wallet creation + Seed backup

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2627]
![image](https://user-images.githubusercontent.com/57008159/201685106-1e8e7eee-cc47-44e0-ac9b-5c08e840c486.png)

**Comment by grdddj** [comment]
Done in [b723445](https://github.com/trezor/trezor-firmware/pull/2610/commits/b723445b6b61d582aafbbedc44a9ec038597844f)

![image](https://user-images.githubusercontent.com/42543243/201601761-e2cf0d34-7a92-4942-9b81-5ecced6a5ef4.png)

**Comment by Hannsek** [comment]
007 - text too low
009 - `Confirm` instead of `Hold to begin`
013, 015 - these screen are not supposed to be here.
017 - unnecessary as 019 says the same.
`Backup is done` screen is missing
085 - `Check phrase` instead of `Check backup`, text shouldn't be **bold**
087-096 - `Select word X/Y` instead of `Select X word` _(we don't have to change that)_
099 - duplicate of 019

**Comment by grdddj** [comment]
> 007 - text too low
> 009 - Confirm instead of Hold to begin

These screens are shared with `recovery`, so the button on the right side will be the same in both cases.

> 013, 015 - these screen are not supposed to be here.

This would however mean that users would not be able to skip backup. It is a good thing, but it is changing the flow we have. Do we really want to enforce the backup?

> 017 - unnecessary as 019 says the same.

17 is what we do generally right now, 19 is specific for `model R`. Do we want to skip `17` therefore?

> Backup is done screen is missing

> 087-096 - Select word X/Y instead of Select X word (we don't have to change that)

The "st", "nd", "rd", "th" can be done, we already do it somewhere. I see I am also not centering that, will do. 

> 099 - duplicate of 019

That is because I have entered a wrong word and therefore it started from the beginning. Is it alright?

**Comment by Hannsek** [comment]
User would firstly _create_ new wallet and then back it up with the seed. Different header than in `recovery` flow.
-> changed first 2 screens and added one more screen with `skip backup`.

Drop `017`.

099 is alright.

**Comment by Hannsek** [comment]
New design/copy/screens: 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/57008159/208418797-540ce77e-bb19-427b-bd4a-dfd5b40e7b6f.png">
