### ISSUE TITLE
Softlock behaves incorrectly with CoinJoin

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#2651]
from Slack:

> Apparently the soft lock during coinjoin behaves somewhat unexpectedly. I left the device alone with lock time 10 min (afaik default) and after few hours, the device is still not locked. Looks like the API calls around coinjoin are resetting internal counter, which they shouldn't IMO.

Presumably the device should not be usable, but CoinJoin messages should be allowed to run through.

With current softlock implementation any USB message will reset the timer.
We might want to differentiate "soft" lock touch (done by an USB message) from a "hard" touch (done by user interaction).
A "hard" touch resets the internal timer. A "soft" touch keeps the timer running, but if there are any "soft" touches registered at the end of the period, the locking will not shut down the current workflow.

To test: CoinJoin operations (via `DoPreauthorized`) are allowed to run even if the device is currently locked. Does this actually work, i.e., doesn't the signing process somehow implicitly rely on storage being unlocked?

**Comment by hynek-jina** [comment]
This needs to be fixed before Trezor Suite 23.2.1 release

**Comment by andrewkozlik** [comment]
> With current softlock implementation any USB message will reset the timer. We might want to differentiate "soft" lock touch (done by an USB message) from a "hard" touch (done by user interaction). A "hard" touch resets the internal timer. A "soft" touch keeps the timer running, but if there are any "soft" touches registered at the end of the period, the locking will not shut down the current workflow.

Makes sense.

> To test: CoinJoin operations (via `DoPreauthorized`) are allowed to run even if the device is currently locked. Does this actually work, i.e., doesn't the signing process somehow implicitly rely on storage being unlocked?

IIRC we have a device test for this and I tested it manually too. It uses `APP_COMMON_SEED` in the session cache.

**Comment by mmilata** [comment]
Tested this with Suite, the idle timer is woken up by `SetBusy` and workflows starting with `DoPreauthorized`. Btw the coinjoin proceeds fine even when device is locked.

The idle timer is touched from following places (plus user interaction):
* [workflow.py](https://github.com/trezor/trezor-firmware/blob/c21cf87c53f79ad8de9d0549bb714cd08f9b46a0/core/src/trezor/workflow.py#L38), at the start of each workflow
* [wire/\_\_init\_\_.py](https://github.com/trezor/trezor-firmware/blob/c21cf87c53f79ad8de9d0549bb714cd08f9b46a0/core/src/trezor/wire/__init__.py#L197), in `read` and `read_any`, i.e. every time a message is decoded inside a workflow
* [apps/base.py](https://github.com/trezor/trezor-firmware/blob/c21cf87c53f79ad8de9d0549bb714cd08f9b46a0/core/src/apps/base.py#L372), in `reload_settings_from_storage()` called from `boot()`, i.e. every time a workflow restarts

The last one I don't know what to do with it, if I don't restart the timer I lose it entirely due to session restart, there don't seem to be a way to get hold of the old deadline?

**Comment by matejcik** [comment]
> The last one I don't know what to do with it, if I don't restart the timer I lose it entirely due to session restart, there don't seem to be a way to get hold of the old deadline?

true, that is not tracked at all currently. ISTM you could just place the value as a global in `storage/cache.py`, that should persist through the restart? and then bump it every time in addition to extending the deadline
