### ISSUE TITLE
UI2: send transaction style update

### ISSUE THREAD

**Issue by mmilata** [trezor/trezor-firmware#2680]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/85857/207273189-13fb5855-b1b4-4358-8701-18e8182111c8.png">

fixes #2151

**Comment by Hannsek** [comment]
Figma file here: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=4081%3A19006&t=VxjZTbyYG85Yz2AV-1

**Comment by Hannsek** [comment]
New design is coming. For now, this is blocked.

**Comment by mmilata** [comment]
Is this still blocked or is the figma design ready now?

**Comment by Hannsek** [comment]
Still not ready, I hope it will be ready next week…

**Comment by Hannsek** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/57008159/217881822-106c2d04-be02-4889-926a-375ac4f28151.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/57008159/217882317-4dfffff5-c7a3-4cda-bcc6-12b720938aaa.png">


Figma file: https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=6276%3A46984&t=fVkX6Rym50TQFKbi-4

Design is ready @mmilata. For now we won't use the chunks when displaying address. Later on we will use it.

**Comment by andrewkozlik** [comment]
In the `recipient #1` screen:
- I think showing the currency in the account label is open for discussion. It should be the same as the currency that we are spending. If it's not, e.g. we are sending LTC to a BTC path, then it seems more appropriate to show the path, than trying to assign a name to it.
- I think we really need to use the word "account" in the account label. `L. SegWit #223` just seems unclear what it means, i.e. `L. SegWit account #223`.

**Comment by Hannsek** [comment]
I agree with both of your points. 
<img width="212" alt="image" src="https://user-images.githubusercontent.com/57008159/219284473-7526a722-2cd0-4838-8504-44965fbb936e.png">

sending LTC to a BTC path is allowed only behind safety checks, right?

**Comment by andrewkozlik** [comment]
> sending LTC to a BTC path is allowed only behind safety checks, right?

Probably yes, but I think there might be some coin combinations which allow it even without safety checks. Those that have fork ID defined may allow it (Bitcoin Cash, Bitcoin Gold, Bitcoin Private). But my point is that it doesn't seem to make sense to assign a name to the account in that case, because the user will not see the incoming transaction in their Bitcoin account. If there is a coin name in the account label, then it should represent the network, not the path. (I think in the T1 implementation it actually represents the path, which is why I am saying it's open for discussion, because I don't really understand the rationale for that.)

**Comment by Hannsek** [comment]
![image](https://user-images.githubusercontent.com/57008159/221595776-8ef00885-91db-41be-a854-b22f9a964e23.png)
