### ISSUE TITLE
Shamir Persistence

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-firmware#270]
Child of #269 

USB will be turn on on the beginning (Wallet turns on recovery).
Button for share input will be only on device. Wallet will show info about that the Shamir recovery is in process and also info about how many shares are missing to reach the threshold. Firmware will also allow to choose between adding another share and aborting the process. After turning on already initialized device, recovery informs device about how many shares was already added, and how many shares are missing to reach the threshold. Threshold is shown after adding first share. Persistence is turned on immediately after turning on recovery.

**Comment by ZdenekSL** [comment]
Child of #269

**Comment by tsusanka** [comment]
Actions items:
- [ ] Persistence starts directly after Recovery confirm page. Words count selection is part of the persistency. That means BIP-39 will be somewhat persistent as well.
- [ ] On homescreen provide info about the progress. If a single share was already entered, we inform how many shares are remaining to reach the threshold. Otherwise we simply show "Enter first/any share" because we do not know the threshold yet.
- [ ] On homescreen offer a button to input share or cancel the process (canceling is equal to wipe - not in dry run!).
- [ ] Send info into Wallet. That this is a Recovery and info about remaining and threshold.

**Comment by tsusanka** [comment]
Also let's increase the iteration exponent to 1.

**Comment by tsusanka** [comment]
Merged in #347. Still waits for some tests in #342
