### ISSUE TITLE
UI2 - receive flow

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2720]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/57008159/213660293-d56d6ced-22df-402f-9312-c3e4f08dd20c.png">

With `x`, users would immediately go back to address view.
With `i`, users would go to the QR code screen.
User would be able to swipe from the QR code back to the address view and vice versa. So this feature would be quite hidden.

**Comment by matejcik** [comment]
how about the xpub flow for multisig?

**Comment by TychoVrahe** [comment]
since the QR button is relatively small, there might be some difficulties touching it correctly. I fought with simillar issue when implementing bootloader UI in #2306 , this is what i came up with (touch area larger then the visual button): https://github.com/trezor/trezor-firmware/blob/ec51cb72d14d79b1689f9a11bd2441a736f01223/core/embed/rust/src/ui/model_tt/component/button.rs#L74

**Comment by Hannsek** [comment]
note: Account names from model R branch
