### ISSUE TITLE
Refactoring storage.py

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-firmware#274]
Child of #269 
Refactoring storage.py

**Comment by tsusanka** [comment]
Waits for review in #295

**Comment by tsusanka** [comment]
Merged in https://github.com/trezor/trezor-firmware/pull/295

**Comment by tsusanka** [comment]
@andrewkozlik as discussed, this is what we need to work with for Shamir backup in storage:

Recovery:
- get identifier of currently entered shares (to warn on incorrect share)
- get indexes of shares that were already entered (to warn on duplicates)
- is recovery in progress?
- get threshold
- get remaining count
- get length of the shares (num of words)

Common:
- get identifier
- get iteration exponent

-------

Questions:
1. Should we store threshold, identifier, remaining and length of shares, if it can be found from the mnemonics that are stored? _I'm voting for yes, because it seems cleaner and it will be deleted when the recovery is finished._

1. How do we store the seperate shares?
  - a) as whole words
  - b) parse and store only the relevant "secret" part

_Whole words are currently easier to implement, but it's not that big of a deal._

1. How to store shares' indexes?
 - a) key = index 
 - b) store shares sequentially and indexes somewhere else (how? bitmap?)
 - c) store shares sequentially, do not store indexes and parse all the shares all the time

_Option a) has the disadvantage that we have to loop through all the possible indexes to find shares. This is low (16) for single-group mnemonics but higher (256) for multiple groups. I'm still slightly in favour of this option, because we can find if some share with some index was already entered very easily._
