### ISSUE TITLE
Trezor Model T does not work as an Apple Security Key

### ISSUE THREAD

**Issue by DavidVeksler** [trezor/trezor-firmware#2784]
**Describe the bug**

I am able to add a Model One as an Apple Security Key.  
However, when I try to add a Model T, I am prompted to register on the Trezor screen, but when I confirm, 
I get the error "HTTPError: Your request could not be completed." on the "Add Keys" dialog.

Same issue reproduced in both MacOS and my iPhone.
Once the key is added in Model One, I can use my Model T (with the same seed) as a key as well.

**Info:**
-   OS: MacOS 13.2 and iOS 16.3
-   Firmware Version: Trezor Model T 2.5.3; Model One: 1.11.2

**How to reproduce**

1. Navigate to your iCloud Profile
1. Go to "Password and Security" screen in either iPhone or MacOS
1. Click "Security Keys"
1. Try to add Model T as the key

**Expected behavior**
Trezor is added as a Security Key

**Additional context**
Apple says that any "FIDO Certified" FIDO2 key is supported: https://support.apple.com/en-us/HT213154
Neither Trezor is FIDO certified, so why does the Model One work and the Model T does not work?

**Comment by bosomt** [comment]
@DavidVeksler 

can you please share more information how to navigate to add security section  ?
I was not able to find dd key in `Password and Security`  in iPhone or macOS v 13.1 even i have 2FA enabled


<img width="471" alt="image" src="https://user-images.githubusercontent.com/31506317/216298343-008803aa-87ba-4296-a11d-d2be684df96d.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/31506317/216298386-eabfecd4-1bd7-4301-8008-2e3fca586b9a.png">

**Comment by andrewkozlik** [comment]
The Trezor T implements FIDO2 and uses "self attestation" by default. Trezor 1 implements only the older U2F protocol, which supports only "basic attestation". So maybe the reason for this is that Apple accepts only basic attestation. We can override the default attestation for Apple devices on Trezor T, but I am unable to reproduce this issue.

**Comment by DavidVeksler** [comment]
> can you please share more information how to navigate to add security section ?

This feature was just added in MacOS 13.2 and iOS 16.3

**Comment by bosomt** [comment]
upgraded to 13.2
and i have to wait a little

![image](https://user-images.githubusercontent.com/31506317/216402030-d2f738b8-32a1-4ae3-843b-66a2785f9978.png)

**Comment by Kl-11** [comment]
Hey @andrewkozlik - thanks for looking at this. Any updates? Facing the same issue here.

**Comment by andrewkozlik** [comment]
It doesn't seem to be related to attestation. I prepared a firmware that uses basic attestation for someone from our company to test and they say it didn't work either.

My next best guess is that it could be related to the ClientPin feature, which is not supported on Trezor, because on Trezor you can enter the PIN on the screen, so there is no use for it. But maybe Apple requires it, simply because pretty much all authenticators on the market are single-button devices with no screen. Verifying this hypothesis would require trying to implement the feature, which I don't have the capacity for right now and the result is uncertain.

The most useful thing right now would be to see a transcript of the USB communication between MacBook/Trezor and between MacBook/Yubikey. On linux I can do that with wireshark.

**Comment by Kl-11** [comment]
Thanks @andrewkozlik - does that still applies if it works with the other Trezor model? As I understood @DavidVeksler was saying (please correct me if I’m wrong).

**Comment by andrewkozlik** [comment]
It still applies, because Trezor T uses the newer FIDO2 protocol, whereas the Trezor model 1 uses U2F.

**Comment by DavidVeksler** [comment]
I tried to use Wireshark, but it cannot capture USB traffic in MacOS Ventura because USB is not listed as an interface.  I will share the log if someone can suggest a way to do that.

**Comment by prusnak** [comment]
@DavidVeksler here's the wireshark guide for usb capture: https://wiki.wireshark.org/CaptureSetup/USB#macos

Apparently you also need to disable SIP on newer version of macOS (catalina and newer).

**Comment by andrewkozlik** [comment]
1. Disable SIP: https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
2. Look at the list of interfaces `tcpdump -D` you should see something like `XHC0` or `XHC20` in the list.
3. Bring up one of the USB interfaces you saw in the list by executing `sudo ifconfig XHC0 up`.
4. Use wireshark to capture communication with a FIDO2 authenticator that works. (U2F communication such as Trezor One is not interesting in this case. FIDO2 Yubikey would be very interesting. Trezor T is less interesting.)

**Comment by DavidVeksler** [comment]
Thanks @andrewkozlik .  Here is the log from Wireshark:

<img width="425" alt="error message for apple security keys" src="https://user-images.githubusercontent.com/2187285/221701811-312ab85b-8ed9-4b1e-a7eb-905aaefc2d3d.png">

[add apple security key.pcapng.gz](https://github.com/trezor/trezor-firmware/files/10844874/add.apple.security.key.pcapng.gz)

**Comment by DavidVeksler** [comment]
Thanks for looking into it.  Just want to emphasize that once I connect with my Model One, the Model T works fine to sign in. 

Would it help to capture Model One traffic for comparison?

**Comment by andrewkozlik** [comment]
> Would it help to capture Model One traffic for comparison?

No. I am afraid not. The traffic is perfectly fine. Apple is not accepting the registration. It could be a bug on their side or an intentional restriction. It's just guesswork now.

However, I am not convinced that it's intentional given that the Model One works and given what they state on their site: "_If you choose a different security key, you should choose security keys that are FIDO® Certified_ [...]". They are not saying you have to use a certified authenticator.

I will need to think about whether we can somehow force fallback to U2F for Apple registration. It could also be that they don't like the size of the FIDO2 credentials, which are larger than the U2F credentials generated by Model One.

**Comment by andrewkozlik** [comment]
I prepared a firmware which uses smaller credentials and a colleague of mine was able to use it to do a successful FIDO2 registration with Apple. Unfortunately, when he tried registering again a few days later, it gave him the error below and it did not even show the registration request on Trezor. That would seem to indicate that Apple might be refusing Trezor's AAGUID, which it didn't do before. @DavidVeksler can you try to register again with your Trezor T and tell me if the behavior has changed for you too?
![image](https://user-images.githubusercontent.com/42678794/226288521-d6856696-218e-4771-bcb2-3df0a0989fef.png)

**Comment by andrewkozlik** [comment]
Update: @DavidVeksler  please ignore the previous comment. It looks like @vdovhanych is banned from registering any FIDO/U2F authenticators right now. I guess he was testing too much.
