### ISSUE TITLE
Recovery: Add a return button to go back when entering words

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#286]
Child of #269 
There is currently no back button when entering words. If I confirm a word and then realize it was wrong, I have no way to go back.

A simple solution is to add a simple backspace button when there is no input in the keyboard, which will take the user one screen back:

![Screenshot from 2019-06-25 09-08-11](https://user-images.githubusercontent.com/1835345/60332243-b017ba80-9996-11e9-8827-1aaa5df15ecf.png)

We might need to shorten the text. @bentonoliver could make up the wording? Consider doing https://github.com/trezor/trezor-firmware/issues/285 along with that.

**Comment by tsusanka** [comment]
@ZdenekSL I'm not sure if we want do this as part of Shamir 2.0 so I'm leaving this up to you (or up to the planning ceremony).

**Comment by prusnak** [comment]
Let's do this as part of Shamir 2.0, please.

We can use the backspace button to discard the latest word entered and go one word back.

**Comment by ZdenekSL** [comment]
With UX designer, specify the text for a screen if we add backspace.

**Comment by tsusanka** [comment]
Discussed with Petr and Matej that this is quite minor issue, which will affect all other users. So we think we should not implement this.

Reasons:
- Users enter the words carefully, so mistakes should occur rarely.
- Persistence will make this easier - only the one specific share needs to be entered again.
- It adds a risk that user will return by mistake.
- It is non-destructive operation if I make a mistake. The worst case scenario you have to enter 20 (or 33) words again (3 min? 5 min?).
- Most of the users will fill in the words correctly with no need for backspace button.

Example: 
Out of 1000 users will do recovery. Out of them 10 people will make a mistake. Because of those 10 people we'd modify the UI (show backspace and shorten the text) for the remaining 990. Those numbers are though a guesstimate.

**Comment by ZdenekSL** [comment]
Ok, just for clarification, if I add share, that has a wrong word in it, I can add the same share, with the correct word and it will pass. Correct? If so, please close this issues, we can reopen it if we have user feedback about the need of backspace.

**Comment by tsusanka** [comment]
> Ok, just for clarification, if I add share, that has a wrong word in it, I can add the same share, with the correct word and it will pass. Correct?

If you enter a share, which is incorrect (some word wrong / missing etc.) we'll let you know and allow you to enter the share again. Does that answer your question?

**Comment by ZdenekSL** [comment]
Yes, thank you.

**Comment by Hannsek** [comment]
I quite often enter different word and I have to go through the whole process again. I believe we can crack this either by suggested button or by adding this functionality as a swipe.

**Comment by Hannsek** [comment]
**T2B1:** Use [this icon](https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Firmware?type=design&node-id=8288-87863&mode=design&t=ZiP9jHmp6MdNMlzF-4) with the text `RETURN` instead of `DELETE` button when no symbol is entered. Middle button should be `SELECT`, we can change it everywhere to `SELECT` instead of `CONFIRM`.
<img width="209" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/e745ab61-7dfa-4580-9f9d-c2557e32db49">

**T2T1:** Let's just do it silently here. So swipe from left to right will trigger the same action as "RETURN" from above.

User will be brought back to the last screen with the letters typed in. See below:
![image](https://github.com/trezor/trezor-firmware/assets/57008159/bee1d933-63d4-4443-b8f9-078d4371b393)
<img width="615" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/ee87d3d5-b790-4137-b43a-d26dbf76f60e">

**Comment by matejcik** [comment]
"return" sounds like "exit the whole process", or maybe "enter" :)
"previous" would be nicer? or "back"

**Comment by Hannsek** [comment]
The copy is not final.

**Comment by b-irving** [comment]
I think `Previous` works best here.

**Comment by Hannsek** [comment]
Thanks, then please use “previous”.
