### ISSUE TITLE
"Never make a digital copy" screen displayed after the backup process

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-firmware#287]
TT 2.1.2 a5d7f2

Expected:
User is informed they should never make a digital copy of the shares before they are supposed to make a backup.

Actual:
The "Never make a digital copy" screen is displayed **after** the whole backup process.

**Comment by tsusanka** [comment]
This is quite easy to do, but I'm not sure this wasn't intentional. I agree though.

@jpochyla any particular reason why did you put it at the end? Or was it a mistake?

**Comment by tsusanka** [comment]
This is a bug. It's quite easy to fix (see tsusanka/note-fix branch), but we need to decide what will be on the final page, because the warning is currently Shamir's last screen:

![Screenshot from 2019-06-28 16-17-12](https://user-images.githubusercontent.com/1835345/60349620-41e8ed00-99c2-11e9-90e7-05f9f8d1cae1.png)

@bentonoliver will think up wording, suggestion:

Use the backup
to recover your
wallet if you ever
lose the device.

**Comment by tsusanka** [comment]
@bentonoliver so I'm using the text as above?

**Comment by tsusanka** [comment]
We now have these two screens, one after another at the end, which might seem cumbersome. We might consider removing the first one, but I'm leaving it as it is for now.

![emu00000000](https://user-images.githubusercontent.com/1835345/61205707-1d468200-a6f1-11e9-84f1-4abf9cbd11af.png) ![emu00000000](https://user-images.githubusercontent.com/1835345/61206068-f3418f80-a6f1-11e9-9d44-6371180101d8.png)
