### ISSUE TITLE
RBF screens copy adjustment

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#2991]
Edit: 
<img width="394" alt="image" src="https://github.com/trezor/trezor-firmware/assets/57008159/847b5bd2-9d7c-4ab4-b791-f5c998eae6c2">

**Comment by mmilata** [comment]
Re: first screen: we currently display  what kind of replacement is going on in the title:
* PayJoin
* Finalize transaction
* Meld transactions
* Update transaction

Do we really want to hide this information?

**Comment by Hannsek** [comment]
Let's talk about this on standup.

**Comment by mmilata** [comment]
For context the logic for choosing the subtitle is following. The replacement transaction flow happens when client sends a `SignTx` call with at least one input or output referring to an original input or output it is replacing.

* If the external inputs (i.e. not belonging to the walled) of the new tx form a superset of the original external inputs then `PayJoin` is displayed.
* If the tx being signed has RBF disabled show `Finalize transaction`.
* If the current inputs/outputs refer to more than one original transaction show `Meld transaction`.
* Otherwise show `Update transaction`.

Also the TXID displayed refers to the _original_ transaction so changing the title to `New transaction ID` is wrong. In case of `Meld transaction` the screen is shown multiple times, for each original transaction.

**Comment by Hannsek** [comment]
> Also the TXID displayed refers to the original transaction
Are you sure about this? I believe it is the new one, but I'll try it tomorrow.

**Comment by mmilata** [comment]
I didn't test it, it is my understanding of the code that handles it: https://github.com/trezor/trezor-firmware/blob/core/v2.6.0/core/src/apps/bitcoin/sign_tx/approvers.py#L260

**Comment by Hannsek** [comment]
You were right, it is the old one.
