### ISSUE TITLE
Shamir: Refactor mnemonic_bip39 and mnemonic_slip39

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#301]
They are two seperate files currently, but some of the logic might be merged. For consideration, it might be better as it is.

**Comment by tsusanka** [comment]
Let's do this on top of #331

**Comment by tsusanka** [comment]
Note to the assigne: In #331 I've moved the mnemonic_* files to apps.management.recovery_device folder a renamed them to {bip39,slip39}_keyboard.py. 

I think that was the most important nit-pick. What is left is to consider if we should merge those two keyboards - in other words create some kind of inheritance where we have Keyboard class with common stuff and then Bip39Keyboard and SlipKeyboard as childs. However, I'm really not sure this is desired/needed so let's do it only if it makes sense!

@ciny I think you can take this one, when you're ready.

**Comment by ciny** [comment]
@tsusanka I've had a look at this:
Prompt and KeyButton can be moved to some common_keyboard.py easily. With this we should probably use keyboard_*.py pattern.

When it comes to *Keyboard and InputButton - Since we don't have access to the abc module we can't enforce contracts from base classes without doing some contract checks of our own. I had a go at it and it adds a lot of sketchy boilerplate to save about 50 duplicate lines. IMHO it's not worth the potential footgun.

**Comment by tsusanka** [comment]
Ok, let's not do it. Maybe it's not worth anything at all then? Moving out Prompt and KeyButton may cause more confusion than good. So maybe let's just do the rename? I agree with that.

**Comment by ciny** [comment]
Ok, I'll just rename the files then and submit a PR.
