### ISSUE TITLE
Add model field to vendor header

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#3028]
We need different vendor headers for different models because we intend to use different signing keys. Also, different model VHs are themselves going to be signed by different keys baked in different bootloaders.

While there is no _technical_ requirement to have the model field in VH, it costs very little to put it there and greatly simplifies management of VHs. There are 14 unused bytes in the VH, so we can fit the four-byte `hw_model` field easily.

I don't think we need `hw_revision` - the VHs should be common for all revisions of the same model, no?

Unsure about `monotonic`. I don't entirely understand its role in bootloader / firmware headers. But probably not necessary for VH either.

cc @TychoVrahe @prusnak 

---

I believe firmware can completely ignore this field in the VH and only check the firmware field. This saves us the headache of having to special-case T2T1 to be equal to 0000000. All treatment of `hw_model` would only happen in our tooling.

---

alternatives:

1. use same signing keys for T2T1 and T2B1 (and possible future T2 platform models at least)
    * seems undesirable from the security hygiene standpoint
2. use different signing keys but keep VHs as-is and differentiate based on which keys they have / how they are signed / file names / etc
    * doable but impractical, esp. in signing tools where we want to be extra sure about what we're signing

**Comment by TychoVrahe** [comment]
I think we don't need neither `hw_revision` nor `monotonic` version in vendor header.

- i think its reasonable to have same VH for all `hw_revision`s (upgrading the revision is mainly done during development, not sure if this is much relevant once the model is released. but who knows what future holds)

- `monotonic` version is used in bootloader header, which is checked by firmware when replacing bootloader - so that firmware doesn't downgrade bootloader which would brick the device (unless there is an SD card slot that can re-upgrade the bootloader). Useless in VH.
