### ISSUE TITLE
Very low contrast in recovery words

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#3259]
![image](https://github.com/trezor/trezor-firmware/assets/42201/efa0f8e4-0969-4a4b-bda9-e6e31a9f9173)

On real device it is almost impossible to see the last two letters of the word error

version 2.6.1

**Comment by Hannsek** [comment]
The easiest solution is to use GREEN_DARK when there is green button but still use GREY_LIGHT when the button is grey.

**Comment by Hannsek** [comment]
Also, the pressed button should not be grey but GREEN_DARK, in that moment, the text should be white.

**Comment by bjorn** [comment]
I ran into this problem when recovering a wallet last week. The lengthy process of typing in my 24 words had failed the first two or three times, since I did not notice that the auto-completion for "sun" wasn't "sunny" but rather the word "sun" itself. :-/

Especially since the whole button turns green, it should be made real clear what word will be chosen then. Because not in all cases where the button turns green, is it actually the right word!
