### ISSUE TITLE
Ripple: try out large numbers in amounts

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#327]
Reported via Support ticket.
Unable to reproduce. 

browser type - Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
OS - Windows 10 version 1803
Trezor Model T
firmware 2.1.1

address we are  trying to send funds to - rwTXopz15WRkXJiD5X2mbojefLZK3RGdYX destination tag 20

Log is attached
[ripple_log.txt](https://github.com/trezor/trezor-firmware/files/3386133/ripple_log.txt)

![ripple](https://user-images.githubusercontent.com/31442634/61123174-fc3d2180-a4a3-11e9-9d66-9d2c46e352bd.jpg)

**Comment by pankrats** [comment]
I sent some ripples to rwTXopz15WRkXJiD5X2mbojefLZK3RGdYX with destination tag 20 and everything went smooth. 

https://xrpscan.com/tx/B6E1CE50EBBF8447FA163737582AE2C2DA020DA18EF30F6384196946CE39D985
![image_from_ios](https://user-images.githubusercontent.com/31442634/61123287-4c1be880-a4a4-11e9-9c34-7b5d5b13eb7c.jpg)

**Comment by tsusanka** [comment]
Note to self: try out the amount. 10005849368 is bigger than 2^32 so there might be some overflow or whatnot.

**Comment by tsusanka** [comment]
@ciny if you'd like to look at this one, feel free to do so.

**Comment by tsusanka** [comment]
We had this [check](https://github.com/trezor/trezor-firmware/blob/tsusanka/iss270-persistence/core/src/apps/ripple/serialize.py#L89) to see if the amount is not higher than the maximum allowed.

However, the maximum as defined in [Ripple's docs](https://xrpl.org/basic-data-types.html#currencies) is most likely in XRP and not in drops ("satoshi" equivalent), which I haven't realized.

Since 100058493680 is higher than the maximum (100000000000), this raised an error. I've fixed this  by modifying the value to the maximum in drops.

**Comment by tsusanka** [comment]
Btw: if we would correctly send wire.ProcessError instead of ValueError exception it'd get propageted into Wallet and it'd be easier to debug. I've created an issue for that: https://github.com/trezor/trezor-firmware/issues/332
