### ISSUE TITLE
USB Read/Write Endpoints Are Interrupts

### ISSUE THREAD

**Issue by MelbourneDeveloper** [trezor/trezor-firmware#330]
It appears that there are no bulk transfer endpoints on the device. This is probably the case for Trezor Model T, but my experiments show that this is the case for Trezor One. When communicating with a USB device, the endpoint would normally be bulk. Interrupt endpoints are not meant for transferring large amounts of data. They are only meant to be polled for data, and APIs built around this usually make it difficult to communicate. For example, in UWP, you cannot directly read from an interrupt endpoint - it will raise an event.

E.g.

![image](https://user-images.githubusercontent.com/16697547/61180798-909fb380-a65f-11e9-89a7-3f4d36056a0c.png)

The above is difficult to deal with. Bulk would be better.

Here you can see this app looks for interrupt endpoints.

https://github.com/trezor/trezor-android/blob/b5211751556fde996c185025b21847af459db96c/trezor-lib/src/main/java/com/satoshilabs/trezor/lib/TrezorManager.java#L145

https://github.com/trezor/trezor-android/blob/b5211751556fde996c185025b21847af459db96c/trezor-lib/src/main/java/com/satoshilabs/trezor/lib/TrezorManager.java#L149

**Comment by prusnak** [comment]
This applies for both Trezor One and Trezor Model T.

Originally, Trezor used HID protocol for achieving maximum compatibility without the need for the drivers and HID does not support bulk transfers.

With WebUSB we might leverage the bulk transfers, but I'd rather not at the moment, because it would break compatibility with all existing implementations.

For now, this is a WONTFIX, but we might (I repeat might) reopen this in future.
