### ISSUE TITLE
Pyblake Installation Failure & utime Module Missing When Building Trezor Firmware (v0.1.3-130-ge736d389f) on Linux with Python 3.11.6

### ISSUE THREAD

**Issue by naiyoma** [trezor/trezor-firmware#3587]
**Describe the bug**
I'm working on #2540, but I'm encountering difficulties building the project locally and running files. Although I've noticed the utime module exists in other files, I still encounter errors related to utime not being found when I run this `poetry run python3 src/apps/common/request_pin.py file` 

**Firmware version and revision**
trezor-client/v0.1.3-130-ge736d389f

**Desktop/smartphone setup (please complete the following information):**
 - OS: [Linux --version 23]
 - Browser [Chrome]
 - python version -- 3.11.6

**To Reproduce**
since I am setting up the project for the first time, followed these steps
1.git clone --recurse-submodules https://github.com/trezor/trezor-firmware.git
2.cd trezor-firmware
3.poetry shell
4.poetry install

first error after poetry install
```
- Updating trezor (0.13.9 /Projects/trezor-firmware/python/src -> 0.13.9 /home/ubuntu/Projects/trezor-firmware/python)
 - Installing pyblake2 (1.1.2): Failed
```
  
 I understand that pyblake is not needed since I am using Python 3.11

 Therefore, I continued building the emulator by following these instructions.

`sudo apt-get install scons libsdl2-dev libsdl2-image-dev llvm-dev libclang-dev clang`
`rustup default nightly`
`rustup update`
`make build_unix` (outputs the following error)
![Screenshot from 2024-03-07 15-21-12](https://github.com/trezor/trezor-firmware/assets/40592031/2c50ddc7-e74b-43b1-9ccd-b84c81c708ac)

**Expected behavior**

After setting up the project and running poetry install i expected to be able to run this file poetry run python3 src/apps/common/request_pin.py  having access to all the modules in micropython and utime
But instead i get this as the output 

```
Traceback (most recent call last):
  File "Projects/trezor-firmware/core/src/apps/common/request_pin.py", line 1, in <module>
    import utime
ModuleNotFoundError: No module named 'utime'
```

**Additional context**
Does Trezor offer alternative communication channels besides the forum (https://forum.trezor.io/), which currently seems unavailable?

**Comment by matejcik** [comment]
> when I run this `poetry run python3 src/apps/common/request_pin.py file`

this will never work

first off you're running in your local cpython, but you need to run it in our micropython binary (that's where the utime module is a builtin)

second, running that file as a separate script won't work either because it's an import of something or other. you can write `something.py` that imports something from that file, and then run `./build/unix/trezor-emu-core something.py` to import it

usually you would just run the emulator and use trezorctl to trigger a flow that executes your changed code. that's the easiest way to go

> `make build_unix` (outputs the following error)

there is not _nearly enough_ context for me to identify the problem.

> Does Trezor offer alternative communication channels

for development help you can visit `trezor-community` channel on Gitter
