### ISSUE TITLE
Send ETH (EVM)

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-firmware#3858]
**Design:** [Figma](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?m=auto&node-id=26%3A4182&t=OdRrLVz4xK6xA634-1)

**Comment by ibz** [comment]
Here are screenshots from the other screens of the flow, as they are now in my PR...

![image](https://github.com/user-attachments/assets/9580fde2-e553-4f55-898e-29794fbfc660)

Note: *Account info* screen missing for now, since we don't have the account # and wallet info...

![image](https://github.com/user-attachments/assets/aca5e439-d951-414a-ae60-415504a6f8a4)

![image](https://github.com/user-attachments/assets/8257a595-3788-467e-bdcc-341b07d27372)

![image](https://github.com/user-attachments/assets/0171dd93-1f45-45e7-b131-12bb2e5eabdb)

![image](https://github.com/user-attachments/assets/4a787bcd-adbb-44fb-b670-4c9f86ac12b1)

![image](https://github.com/user-attachments/assets/6ef2d2a0-3b64-4b88-8cd7-f4e54b652786)

![image](https://github.com/user-attachments/assets/9f5996dc-b793-4faa-9a88-839c96a9f5b7)

**Comment by obrusvit** [comment]
@ibz yes, use the current implementation of success screen. They can fit more text.
Figma success screens are a little bit outdated.

**Comment by ibz** [comment]
BTW, I reused this new flow also for the staking part, which now looks more like the Figma: https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?node-id=160-368&node-type=CANVAS&t=q6Wjn67DNiTujwTm-0

Linked the relevant PR to this issue...
