### ISSUE TITLE
Issue with Ping proto definition in Trezor common repo

### ISSUE THREAD

**Issue by shrimalmadhur** [trezor/trezor-firmware#4091]
Hello, 

I am checking trezor cli and the [Ping](https://trezor.io/learn/a/using-trezorctl-commands) command in that has 3 fields 
```
-b or --button-protection
-p or --pin-protection
-r or --passphrase-protection
```

But the proto definitions in the [trezor-common](https://github.com/trezor/trezor-common/blob/68502be56e9fa2d600b0ff5fdc808a747b7371a6/protob/messages-management.proto#L305-L308) repo doesn't have the same interface. Why is there a discrepancy. As far as I can recall, there used to be fields in `Ping` command before which had pin protection and passphrase-protection

Is there a reason? Did it move somewhere? How can I achieve the same programmatically ?

Let me know if this is not the correct place for this issue or this would count as bug.

**Comment by matejcik** [comment]
We removed the PIN / passphrase thing from Ping because ... uhh ... reasons. I recall something like it was problematic on trezor-core for one reason or another.
I suspect that the actual reason is that "ask the user for PIN" is not actually a functionality that Trezor provides to the host; the PIN is an internal thing. Similar argument can be made for passphrase. These functions are not part of the API surface, they happen when required to accomplish an actual operation.

The matching functionality is also removed from trezorctl: https://github.com/trezor/trezor-firmware/blob/main/python/src/trezorlib/cli/trezorctl.py#L313-L319

The KB article on trezorctl is seriously outdated. The reference on trezorctl is available via `trezorctl --help` or `trezorctl somecommand --help` for each command.

For user-facing functionality questions, Trezor Forum is the best place: https://forum.trezor.io/
For developer questions, there is a Gitter / Matrix channel `trezor-community`.

> How can I achieve the same programmatically ?

The same what? Ping is not really a functional part of the API. `trezorlib.client.TrezorClient` class has functions like `ensure_unlocked()` that will prompt the user for all relevant data. And, as explained above, "ask for PIN" is not an exposed feature because it would serve no purpose.
