### ISSUE TITLE
Skip Threshold prompt if number of shares is 1

### ISSUE THREAD

**Issue by ciny** [trezor/trezor-firmware#463]
If number of shares is 1 then the threshold can also only be one, in that case we can skip this step. We have to make sure it won't be confusing for the user so UX will be needed

**Comment by ZdenekSL** [comment]
We decided that we will hide the screen with threshold if the shares are set to 1 in the group.

**Comment by tsusanka** [comment]
I've implemented this, but I think it's really not a good idea. Example workflow, I start Super Shamir and:

- I set number of shares for group 1 and choose 5 shares.
![emu00000001](https://user-images.githubusercontent.com/1835345/64690309-5badb280-d490-11e9-98df-d5a28126aad5.png)
- I set threshold for group 1 and choose 3.
![emu00000002](https://user-images.githubusercontent.com/1835345/64690310-5badb280-d490-11e9-8c9e-72acb4604726.png)
- I set number of shares for group 2 and choose 1 share.
![emu00000003](https://user-images.githubusercontent.com/1835345/64690311-5badb280-d490-11e9-8dd4-79c69a3ca67b.png)
- Now I am supposed to choose number of shares for group 3. I did not get any confirmation or anything that the threshold is equal to 1 and it is really easy to not realize that I'm setting the number of shares for group 3 instead of the threshold.
![emu00000004](https://user-images.githubusercontent.com/1835345/64690312-5badb280-d490-11e9-97f7-5ba9b620cf1f.png)

I think this does more harm than good.

**Comment by tsusanka** [comment]
Also note, that we already have a screen where you can't set anything. And that's when number of shares is 2, we enforce the threshold to 2 (not in groups threshold):

![emu00000000](https://user-images.githubusercontent.com/1835345/64690901-d0352100-d491-11e9-9298-d564a7cd9fd9.png)

**Comment by tsusanka** [comment]
After discussion with @matejzak we have decided not to implement this, because we believe it confuses people. Petr (UX) seem inclined to leave it as well.

**Comment by sorooris** [comment]
@tsusanka what is the current option then?

**Comment by tsusanka** [comment]
We will have a screen with the threshold even it is equal to 1 and it can't be changed.

![emu00000000](https://user-images.githubusercontent.com/1835345/65225203-ffb4e080-dac4-11e9-932e-5dda06391dc4.png) ![emu00000001](https://user-images.githubusercontent.com/1835345/65225204-ffb4e080-dac4-11e9-96cd-dc7cbca19761.png)
