### ISSUE TITLE
unit tests for process_slip39

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#542]
The function `recover.process_slip39` is untested, and relies on some check being done by the UI.

In particular, it is unclear what would happen if the UI checks failed and the user entered a Slip39 Basic mnemonic first, and a mnemonic *with the same first 2 words* but from a different set second.

There should be unit tests to verify its behavior.

**Comment by tsusanka** [comment]
Do I understand it correctly that because unit tests are run using micropython itself, we can't use `mock` package because it seems there is no port for micropython, is that correct? I didn't find it in [micropython-lib](https://github.com/micropython/micropython-lib) nor did I get any reasonable google search results.

The reason I'm asking is that I need to mock the storage interface. I guess I can do it the simple way where I redefine the functions with some simple lambdas, but it is significantly less powerful than `mock`.

cc @prusnak

**Comment by matejcik** [comment]
> Do I understand it correctly that because unit tests are run using micropython itself, we can't use `mock` package because it seems there is no port for micropython, is that correct?

yes.
we can implement a simple Mock object in ~30 lines that should be good enough for our purposes. an implementation is likely to lie around on StackOverflow somewhere :)

**Comment by tsusanka** [comment]
I've made a separate issue for that: #559. Let's do this issue after that one then.

**Comment by tsusanka** [comment]
> In particular, it is unclear what would happen if the UI checks failed and the user entered a Slip39 Basic mnemonic first, and a mnemonic with the same first 2 words but from a different set second.

@matejcik so you mean first the user enters `extra extend academic ..` which is Slip39 Basic and then `extra extend romp`, which has the same identifier, but different group settings.

**Comment by tsusanka** [comment]
It indeed seems to behave unexpectedly. I'll look into it.

**Comment by matejcik** [comment]
draft PR: #592
