### ISSUE TITLE
Super Shamir - Success messages after finishing share backups are incorrect 

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#564]
The problem is just with the messages.

Steps to reproduce: 
1) initialize the device with super Shamir
2) select 3 Groups, 1st group 3 shares, 2nd group 5 shares, 3rd group 5 shares. 
3) start the backup process, 1st group success messages are all okay
4) 2nd group - after writing down the 3rd share I got the message "you have finished verifying your recovery shares for group 2", but actually I had 2 more shares to go (the shares were displayed to me straight after, no problem here) 
5) 2nd group - when I finished writing down the share 5 (the last share from this group), I got the message "continue to the next share", but actually the group was finished. 
![photo_2019-09-24_11-16-39](https://user-images.githubusercontent.com/31442634/65500711-fe6a2600-debf-11e9-8e41-18e5237fdb2c.jpg)

6) 3rd group - the same issue as in 4.
![photo_2019-09-24_11-27-08](https://user-images.githubusercontent.com/31442634/65500477-a501f700-debf-11e9-9f7a-6128c6fd1875.jpg)

7) 3rd group - the same issue as in 5.

**Comment by ciny** [comment]
We were passing the number of groups instead of number of shares in group to the function displaying the success page. So "you have finished verifying..." message would display after the 3rd share in every group. Faster way to test this is to set the number of groups to 3 and first group to 5, the wrong page will be displayed after the 3rd share out of 5 is entered.
