### ISSUE TITLE
Resolve low memory issue

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#590]
Related:
* #575 monero signing runs out of memory on device
* #194 Measure and plot firmware memory usage
* #174 Investigate CCMRAM usage

Let's discuss:
* when to import modules?
* does making module functions `_private` help?
* where should we call `gc.collect()`?
* should we use `unimport`?
* should we use `gc.threshold`?

**Comment by prusnak** [comment]
Couple of suggested fixes are in this branch:

https://github.com/trezor/trezor-firmware/tree/memory-fix

**Comment by prusnak** [comment]
Handy:

`micropython.mem_info()` and `micropython.mem_info(True)`

**Comment by tsusanka** [comment]
What have I encountered several times in the mypy issue is this: `content.__class__.__name__ == "Paginated"`. I'm wondering if omitting a single import has significant advantage. In other words if we need to keep doing this, because mypy does not recognize it.

**Comment by prusnak** [comment]
Backporting this patch to micropython fork saved 40KB of memory at start: https://github.com/trezor/micropython/commit/64236f5518b443c3f7631a4d6b31e2c8ccc385f4 :tada:

**Comment by matejcik** [comment]
This is no longer a pressing issue, and will be even less with the switch to the Rust UI.
All device tests are now passing on hardware.

There are some sub-issues: #174, #194, but both of those are find as stand-alone issues.

I'm closing this one because we don't currently need it as a separate task, AFAICT.
