### ISSUE TITLE
Some device tests stall when real device is used.

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#591]
This seems caused by DebugLink communication.

**Comment by tsusanka** [comment]
I will confirm, but it seems to me that the only problematic test is test_msg_sd_protect. It gets stuck on the `Please unplug the device and insert your SD card.` warning, which makes sense since there is no SD card present.

Maybe the the test should be skipped if there is no SD card?

cc @andrewkozlik

**Comment by andrewkozlik** [comment]
It makes sense to skip the test if the tests are running on the device and there is no SD card. I suppose we can either
1. add a command-line option to pytest which will skip the test, but you can already do something like `pytest -v -k sd_protect`; or
2. add `io.SDCard().present()` to GetFeatures and skip if it's false and the tests are not running on the emulator.

**Comment by tsusanka** [comment]
> 2. add io.SDCard().present() to GetFeatures and skip if it's false and the tests are not running on the emulator.

Since the tests are run on a device with the debug mode enabled, maybe DebugLinkState is a better choice? And we can add it to Features when it is actually needed by other applications.

**Comment by tsusanka** [comment]
The PR is merged, but I will run the device tests over night to see if it does not stall somewhere else.

**Comment by tsusanka** [comment]
The result of running the tests on a real device on current master (727b7f8cd) is the following:

## 3 errored:

- test_msg_sd_protect.test_enable_disable
- test_msg_sd_protect.test_wipe
- test_msg_sd_protect.test_refresh

Which is correct since I have not provided any additional flags.

## 3 failed:
- test_bip32_speed.test_public_ckd
- test_bip32_speed.test_private_ckd

If I'm correct we are aware of those two - that they might fail. However, does it make sense to keep them then @prusnak @matejcik?

- test_msg_web_authn.test_add_remove

This fails on UnexpectedMessage error, because Trezor does not know neither `WebAuthnRemoveResidentCredential` nor `WebAuthnListResidentCredentials` messages, which I suppose is because of: https://github.com/trezor/trezor-firmware/blob/68a3094b0a8e36b588b1bcb58c34a2c9eafc0dca/core/src/main.py#L53-L55 And we have that because we can't run both debuglink and webauthn on the actual device, correct? Should the test be skipped then when run on a device

**Comment by andrewkozlik** [comment]
We agreed, that we should try moving the `if not __debug__ or utils.EMULATOR` check into `webauthn::boot()` so that only `loop.schedule(handle_reports(iface))` is disabled in the device debug build.

**Comment by tsusanka** [comment]
Webauthn tests fixed via #661 so the only thing left here is to decide what to do with test_bip32_speed tests.

**Comment by tsusanka** [comment]
The last issue moved to https://github.com/trezor/trezor-firmware/issues/663, closing here.
