### ISSUE TITLE
Document how to contribute to core using an example feature

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#691]
Part of #685.

It would be nice to show how to contribute to Trezor by documenting how some feature is added. From protobuf to adding some code in core and tests. An example brought up on our meeting was `set_u2f_counter`.

**Comment by grdddj** [comment]
I tried to create a small `hello-world` feature that could be suitable for documentation purposes. It is currently in [`grdddj/docs_hello_world_feature`](https://github.com/trezor/trezor-firmware/tree/grdddj/docs_hello_world_feature) branch.

It creates new `protobuf` messages, logic for them in `core`, as well as the `trezorlib` functionality to call them. It currently does not cover tests (unittests nor device tests - may be done if we want).

There is no "official" documentation yet, I will write some `README` describing the process in simple steps (which files to create, which to edit, which commands to run...).

I guess we might even preserve the branch with the `hello-world` feature, so that we can have a link to the commit with all necessary changes - 36a8bfe04ae079ed0755366451e86681292c7857. Then somebody can just fill their own logic into this "template" and are ready to go.
