### ISSUE TITLE
macOS: disable CONFIDENTIAL='__attribute__((section("confidential")))' on emulator build

### ISSUE THREAD

**Issue by karelbilek** [trezor/trezor-firmware#7]
on macOS build, `CONFIDENTIAL='__attribute__((section("confidential")))'` does not work and causes error

`error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment
      and section separated by a comma
        static CONFIDENTIAL HDNode node;
               ^
<command line>:2:45: note: expanded from here
#define CONFIDENTIAL __attribute__((section("confidential")))
`

I solved it locally by changing the line in Makefile.include to `-DCONFIDENTIAL=''`; not sure what is the Right Way here

**Comment by malinah** [comment]
I'm proposing this fix:
```c
#ifdef __MACH__
#define CONFIDENTIAL_SECTION "__DATA,confidential"
#else
#define CONFIDENTIAL_SECTION "confidential"
#endif

#define CONFIDENTIAL __attribute__((section((CONFIDENTIAL_SECTION))))
```
Unfortunately the fix requires structural changes to the source code since it's not a plain definition that can be passed through gcc -D option as it is now in `Makefile.include`. 

Can't validate on macOS due to build errors:
* Build system is confusing python2 and python3 scripts.
* Directory missing `/usr/include`.
* Missing `objcopy`.
...

Decide wether legacy should be supported on macOS.
