### ISSUE TITLE
Move multiple vendored dependencies to root /vendor

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#82]

**Comment by matejcik** [comment]
done in https://github.com/trezor/trezor-firmware/tree/matejcik/vendor-move
but there's a catch: when a pull would not be fast-forward, you have to do `git submodule deinit --all` before pulling.
otherwise your working tree is very likely to get into a broken state, which is a little difficult to recover from

so i'm not merging this just yet.

**Comment by matejcik** [comment]
closed via https://github.com/trezor/trezor-firmware/commit/43866407df479278eefa1f7c891dd53c9400a8ea
